### ISSUE TITLE
add describtion for test criteria into IPK-BrAPI-Validator frontend

### ISSUE THREAD

**Issue by langeipk** [plantbreeding/IPK-BrAPI-Validator#1]
As comment by Jack Elendil Lagare (IRRI) <j.lagare@irri.org>, please add a short description what is tested and a example of potential failures to each of the 3 test criteria:

- Schema: Single resources
- Schema: All non-parametric resources
- Data: Full Resource schema and data test

**Comment by martinbaste** [comment]
I added a description of what the validator and each test does. I'll close this and any new UI suggestions can be added as new issues.
6f7df01
