### ISSUE TITLE
schemas missing fields

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/IPK-BrAPI-Validator#13]
V1.0 deprecated fields should be acceptable in the return objects of a V1.1 call

/schemas/v1.1/germplasm/germplasmDbId/pedigree.json -> parent1Id, parent2Id, should be accepted, but not required

/schemas/v1.1/locations.json -> instituteAdress,  should be accepted, but not required

/schemas/v1.1/variables.json -> submissionTimestamp, should be allowed

/schemas/v1.1/ontologies.json -> description, should be allowed

**Comment by martinbaste** [comment]
Thanks! I'll update the live version soon
