### ISSUE TITLE
Allowing extra/deprecated parameters

### ISSUE THREAD

**Issue by martinbaste** [plantbreeding/IPK-BrAPI-Validator#20]
Hi,

We're considering adding an option to allow non-BrAPI defined parameters when validaring resources. This would mean that deprecated parameters and extra parameters would not raise an error or warning. 

The benefit is that it adds extra flexibility when a client/server use extra information.

The downside is that unintentional errors can slip through: mistyped optional parameters won't be detected.

@BrapiCoordinatorSelby (and anyone else using BrAVA), do you think this would be useful?

**Comment by BrapiCoordinatorSelby** [comment]
Yea this could be useful. 
Personally, I like having the validation as strict as possible, so as long as this new option can be controlled by the user so I can turn it off, I'm good with it.

That said, I think deprecated fields should be considered optional fields. They are still technically part of the spec and it is expected that they could be populated. By contrast, extra fields are unexpected for BrAPI, so it makes sense to let the user decide whether or not to expect them in the test.

**Comment by martinbaste** [comment]
Yeah I think we'll keep deprecated in the schemas as optional, so they are accepted in strict or non-strict, and extra fields are accepted in non-strict but not in strict.

**Comment by martinbaste** [comment]
Implemented, public resources and subscriptions are still in strict mode, the same as before. A checkbox allows users to select this mode for custom sets.
