### ISSUE TITLE
markerprofileDbId parameter type

### ISSUE THREAD

**Issue by GuilhemSempere** [plantbreeding/IPK-BrAPI-Validator#23]
I'm testing http://gigwaV2.southgreen.fr/gigwaV2/rest/Rice-MSU7/brapi/v1 using BRAVA and my server generates a 500 error on the "/allelematrix-search POST with markerprofileDbId" call.

The reason is I'm expecting an array as value for the markerprofileDbId parameter, and BRAVA seems to be passing a single String (correct me if I'm wrong).

Looking at this example https://brapi.docs.apiary.io/#reference/markerprofiles/markerprofile-allele-matrix/scores-through-post it looks like it should indeed be an array, what do you think?

**Comment by BrapiCoordinatorSelby** [comment]
#22 should fix this. This issue is ready to close
