### ISSUE TITLE
website problems

### ISSUE THREAD

**Issue by ClayBirkett** [plantbreeding/IPK-BrAPI-Validator#25]
The BrAPI-Validator website is not running  "Test Your Own" any more.
http://webapps.ipk-gatersleben.de/brapivalidator/
I just get and "Internal Service Error" in the message box.

**Comment by langeipk** [comment]
Thanks for reporting! Could you please provide a screenshot.

**Comment by langeipk** [comment]
Thanks for reporting Its reproducible using a valid endpoint url.

**Comment by langeipk** [comment]
Thanks for reporting. It was a deploy problem and was fixed now.
