### ISSUE TITLE
Refreshing the BrAPI endpoint on the home page

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/IPK-BrAPI-Validator#29]
Sometime ago, we changed our URGI GnpIS endpoint URL from https://urgi.versailles.inra.fr/GnpISCore-srv/brapi/v1/ to https://urgi.versailles.inra.fr/gnpis-core-srv/brapi/v1/ in the BrAPI repository (at https://github.com/plantbreeding/API/blob/master/brapi-resources.json). 

It seems that the BrAPI endpoint URL does not update automatically on the website:
http://webapps.ipk-gatersleben.de/brapivalidator/

**Comment by langeipk** [comment]
this is true. It’s a manual triggered update. This is because, not all entries in the GIThub Json repo file where working in the past.

So we will trigger the update and close the issue if the update is done.

**Comment by patrick-koenig** [comment]
The update has now been completed successfully.
