### ISSUE TITLE
store validation reports from periodic test of user specific endpoints

### ISSUE THREAD

**Issue by langeipk** [plantbreeding/IPK-BrAPI-Validator#3]
Please store the last x results from periodic validation of user defined BrAPI endpoints . x is at minimum 2 and may be specified during registration of a validation schedule.  The recent stored reports is linked in the notification e-mail of the last run

**Comment by martinbaste** [comment]
This should be done by commit e0957be, I've left the last 3 reports in the email by default, although it is stored individually per registration, so it is easy to change or set up an option while signing up
