### ISSUE TITLE
Forced to use port 80 in "Test your own"

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/IPK-BrAPI-Validator#30]
TestItemRunner.java line 226
```
if ((Config.get("advancedMode") != null && Config.get("advancedMode").equals("true"))
    && u.getPort() != 80 && u.getPort() != -1) {
    throw new IllegalArgumentException();
}
```
This piece of code means when BRAVA is running in "advancedMode" (ie. in production) and the requested port is not 80, then throw an exception. Why is this check here?

**Comment by BrapiCoordinatorSelby** [comment]
I'm going to be putting some work into BRAVA in the next few weeks with the upgrade to BrAPI v1.3, so I can make the code fix in a pull request if needed. 
I just wanted some feedback if there was a specific purpose behind this check for port 80.

**Comment by langeipk** [comment]
Great news, thanks for supporting to add v1.3 support to BRAVA! Would be nice if a semeautomatic way to generate JSON schema files work.  Regarding the port 80 question: it is indeed a check to ensure that the productive service run at a public port only. This aims to prevent proxy/firewall incompatibility in production mode.
