### ISSUE TITLE
"Test your own" 60 sec timeout

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/IPK-BrAPI-Validator#33]
Description:
When using the "Test your own" page, if a validation request takes more than 60 sec, the request will timeout and no results are returned to the UI

Steps to recreate:
 - Go to "Test your own" tab
 - Enter in `https://test-server.brapi.org/brapi/v1` as the server URL (103 implemented calls in V1.3)
 - Select BrAPI V1.3
 - Click "Test it now!"

Expected:
When the loading spinner stops spinning, the results should be shown.

Actual:
The loading spinner spins for 60 sec (default request timeout), then no results are shown.

**Comment by patrick-koenig** [comment]
Hi Peter,

thank you for the report of this issue. For me it looks like a configuration problem of our Apache proxy server (wo is sitting in front of the Tomcat). Probably a timeout of 60 seconds is set and this is not sufficient for longer lasting tests. I have reported it to our server administrator and he will take care of it as soon as possible.

**Comment by patrick-koenig** [comment]
In addition, I will add a better error catch for such cases in the Javascript frontend code.
