### ISSUE TITLE
Running advanced BRAVA

### ISSUE THREAD

**Issue by mobreza** [plantbreeding/IPK-BrAPI-Validator#35]
There's little documentation on how to configure BRAVA to use a database.

```properties
# H2 Username, password and path
dbuser=
dbpass=
dbpath=
```

- Please update the `config.properties.example` for a HSQL or mysql database (with all properties that control the setup, including a sample connect string)
- ~~How to initialize the database model and any initial data? Genesys uses liquibase for DB schema management.~~ Are database model changes handled in current implementation?

**Comment by mobreza** [comment]
@langeipk I missed the `config.properties.example`. Hold on.

**Comment by langeipk** [comment]
Hi, we use a ORACLE DB to host the BRAVA database. Below you find a example config for this databae. The difference to MYSQL or H2 are the JDBC connect string in property dbpath. 
Please have a lock to[ MYSQL documentation ](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html)

Database model changes in the database is not supported. The creation of database table is performed by servlet initialization. If the expected tables does not existing, they are created in Class DataSourceManager. We use [ormlite](http://ormlite.com/) as object relational mapping  and tested it for H2 and ORACLE. But MySQL should work as well.

-------- example config for ORACLE backend DB -----
dbuser=<oracle-login>
dbpass=<oracle password>
advancedMode=true
dbpath=jdbc:oracle:thin:@ipkoraclehost.ipk-gatersleben.de:1521/ipkoracleservice
http.proxyHost=proxy_xyz.ipk-gatersleben.de
http.proxyPort=3128
https.proxyHost=proxy_xyz.ipk-gatersleben.de
https.proxyPort=3128
adminkey=xxx
mailSmtpHost=imapserver.ipk-gatersleben.de
fromEmailAddress=noreply@ipk-gatersleben.de
fromPersonalName=noreply@ipk-gatersleben.de
senderName=Martin Basterrechea - BrAVa developer at IPK-Gatersleben
contactEmail=basterrechea@ipk-gatersleben.de
baseDomain=http://webapps.ipk-gatersleben.de/brapivalidator
resourceJsonUrl=https://raw.githubusercontent.com/plantbreeding/API/master/brapi-resources.json
testedVersion=v1.2

**Comment by langeipk** [comment]
solved in commit 5487d3abbde3e7ff9189bdb284c7c261010a5d9f
