### ISSUE TITLE
testing germplasm calls

### ISSUE THREAD

**Issue by GuilhemSempere** [plantbreeding/IPK-BrAPI-Validator#44]
I'm testing germplasm calls on https://gigwa-dev.southgreen.fr/gigwaV2/rest/Cassava-4-1_scaffolds/brapi/v1/ and:

POST /search/germplasm appears to work

GET /germplasm/{germplasmDbId} says "missing required resources", and subsequently, so does 
GET /germplasm/{germplasmDbId}/attributes

My understanding is it complains about having no germplasmDbId to pass to /germplasm/{germplasmDbId} but since /search/germplasm did return some data, I guess it should?!?

**Comment by patrick-koenig** [comment]
Dear Guilhem,

It seems that you have not implemented the mandatory resource _GET /germplasm_. This prevents the extraction of a necessary _germplasmDbId_ from the response for beeing used in the consecutive schema tests like e.g. _GET /germplasm/{germplasmDbId}_ or _GET /germplasm/{germplasmDbId}/attributes_. This is expressed by the error message "missing required resources".

The resource _/search/germplasm_ is independent from the _/germplasm/*_ resources. 

germplasmDbIds extractable there are not used in the schema tests that check the group of _/germplasm/*_ resources.

Please implement or provide the GET _/germplasm_ resource to see if it then works. Without any parameters the _/germplasm_ call should list a paginable list of all available germplasm.

Best,
Patrick

**Comment by GuilhemSempere** [comment]
Thanks for providing this clue. It all seems right now.
