### ISSUE TITLE
Failure test the server BrAPI version 2.0

### ISSUE THREAD

**Issue by langeipk** [plantbreeding/IPK-BrAPI-Validator#49]
BRAVA reported for https://test-server.brapi.org/brapi/v2 an internal server. The console output is:

685134 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - Testing Schema
685134 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - Doesn't match schema
685134 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - == cause ==
685134 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - fatal: unable to dereference URI "resource:/schemas/v2.0/Vendor/getVendorPlatesSubmissionidResponse.json#"
    level: "fatal"
    uri: "resource:/schemas/v2.0/Vendor/getVendorPlatesSubmissionidResponse.json#"
    exceptionMessage: "resource /schemas/v2.0/Vendor/getVendorPlatesSubmissionidResponse.json not found"

685134 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - New Request. URL: https://test-server.brapi.org/brapi/v2/vendor/specifications
685653 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - Testing Status Code
685654 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - Status Code Test Passed
685654 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - Testing ContentType
685654 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - ContentType Test Passed
685654 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - Testing Schema
685655 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - Doesn't match schema
685655 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - == cause ==
685655 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - fatal: unable to dereference URI "resource:/schemas/v2.0/metadata.json#"
    level: "fatal"
    uri: "resource:/schemas/v2.0/metadata.json#"
    exceptionMessage: "resource /schemas/v2.0/metadata.json not found"

685655 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - Testing Schema
685656 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - Doesn't match schema
685656 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - == cause ==
685656 [qtp1153329578-27] INFO  de.ipk_gatersleben.bit.bi.bridge.brapicomp.testing.runner.TestItemRunner  - fatal: unable to dereference URI "resource:/schemas/v2.0/Vendor/getVendorSpecificationsResponse.json#"
    level: "fatal"
    uri: "resource:/schemas/v2.0/Vendor/getVendorSpecificationsResponse.json#"
    exceptionMessage: "resource /schemas/v2.0/Vendor/getVendorSpecificationsResponse.json not found"

**Comment by BrapiCoordinatorSelby** [comment]
I was not able to recreate this error. 
Taking a closer look at the log, this might have been a fluke or a deployment issue. 
`exceptionMessage: "resource /schemas/v2.0/metadata.json not found"`

I ran the deployed v2.0 tests against the test server and everything appears to be running as expected.
