### ISSUE TITLE
split the BrAPI endpoint testing site into a report of published reports and individual enpoint test

### ISSUE THREAD

**Issue by langeipk** [plantbreeding/IPK-BrAPI-Validator#6]
Please split the BrAPI endpoint testing site into two:
1.	one quality  report of all published BrAPI endpoints
Each endpoint is tested for [number of correctly implemented resources]/[number of resources in /calls]. The schedule of the test one per week
2.	a submission and test page (template is  the existing BrAVA home page)
Here we do not show a combo box of all BrAPI-GITHUB stored endpoints. Its rather a single textbox to submit the URL with an optional option to store it an include in the report
3.	Implement the access to the report as REST API to provide clients a possibility the retrieve endpoints and their implementation status programmatically

**Comment by martinbaste** [comment]
1 & 2 finished, I'll create a new issue with 3 to separate issues. Feel free to reopen or create new issues regarding any details on the implementation of this issues.
