### ISSUE TITLE
Which branch to use to test BrAPI 2.1

### ISSUE THREAD

**Issue by ydeoliveira** [plantbreeding/IPK-BrAPI-Validator#74]
Hello,

I tried to install BRAVA with docker from master branch but it seems it doesn't include v2.1 of the BrAPI.

Can you tell me which bracnh to use to have the same version than the online instance : https://webapps.ipk-gatersleben.de/brapivalidator/

Thanks !

**Comment by daveneti** [comment]
The master branch has the 2.1 version, so that should work.

I have not used it for a while, because I started on a refactored version of BRAVA (I use this now). It works but I need to do more testing.  That is on the BRAVA_main_2 if you would like to test.

**Comment by ydeoliveira** [comment]
Thank you Guy !

I tried to install BRAVA from sources and that's fine, v2.1 can be tested. 
I tried in a first time to install BRAVA via docker but the image haven't been updated for a while.

Best regards
Yannick
